name: ifs
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=2.1.2
  - tensorboard >= 2.12.1
  - scikit-learn=1.3.0
  - psutil
  - requests
  - tqdm
  - imageio
  - pip:
    - imageio-ffmpeg>=0.4.3
    - pyspng
    - alphashape==1.3.1
    - shapely==2.0.3
    - open3d==0.17.0
